name: dofit
description: DoFit is a Fitness App for keeping you fit and strong.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #here goes the all package that we will use in our DoFit App
  # for Google fonts
  google_fonts: ^6.1.0
  #for All types of screens
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  onboarding: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Images/
 
  